USE bikestoreproject;

SELECT * FROM stores;
SELECT * FROM orders;
SELECT * FROM order_items;

# ========================================================================
# Task 1: Store Performance – Total revenue generated by each store.
# ========================================================================
SELECT 
    stores.store_name,
    SUM(order_items.list_price * order_items.quantity * (1 - order_items.discount)) AS total_revenue
FROM stores
JOIN orders ON orders.store_id = stores.store_id
JOIN order_items ON orders.order_id = order_items.order_id
GROUP BY store_name
ORDER BY total_revenue DESC;

-- INSIGHTS: 
-- Baldwin Bikes leads performance significantly, driving the highest overall revenue. 
-- Conversely, Rowlett Bikes lags behind in gross sales volume, identifying it as a 
-- key location requiring targeted operational or marketing review.


# ========================================================================
# Task 2: Top 5 most sold products by quantity. 
# ========================================================================
SELECT 
    products.product_name,
    SUM(order_items.quantity) AS total_quantities
FROM products
JOIN order_items ON products.product_id = order_items.product_id
GROUP BY products.product_name 
ORDER BY total_quantities DESC
LIMIT 5;

-- INSIGHTS: 
-- These top 5 models represent the primary volume drivers for the business. 
-- High product velocity metrics suggest these items require robust replenishment schedules 
-- to completely prevent fulfillment delays.


# ========================================================================
# Task 3: Customers who placed orders with store names.
# ========================================================================
SELECT 
    CONCAT(customers.first_name, ' ', customers.last_name) AS full_name,
    stores.store_name
FROM customers
JOIN orders ON orders.customer_id = customers.customer_id
JOIN stores ON stores.store_id = orders.store_id;

-- INSIGHTS: 
-- This mapping links consumer profiles directly to regional retail outlets, 
-- establishing local customer distribution layouts. This informs localized 
-- retention initiatives and localized brand marketing campaigns.


# ========================================================================
# Task 4: Total number of products per brand.
# ========================================================================
SELECT
    brands.brand_name,
    COUNT(products.product_name) AS total_products
FROM brands
INNER JOIN products ON brands.brand_id = products.brand_id
GROUP BY brand_name 
ORDER BY total_products DESC;

-- INSIGHT: 
-- Identifies product portfolio variation depth across various brands. 
-- Brands with the highest unique SKU counts dominate catalog availability, 
-- signaling strong supply reliance on specific industry manufacturers.


# ========================================================================
# Task 5: Products with zero quantity in stock.
# ========================================================================
SELECT
    products.product_name,
    stocks.quantity AS zero_quantity
FROM products
JOIN stocks ON products.product_id = stocks.product_id
WHERE stocks.quantity = 0;

-- INSIGHTS: 
-- Serves as an immediate operational trigger list for stockouts. 
-- These products require immediate reorder procurement to eliminate active supply gaps 
-- and prevent lost sales opportunities across affected branches.
