use bikestoreproject;

select * from stores;
select * from orders;
select * from order_items;

#Task 1: Store Performance – Total revenue generated by each store.

select 
	stores.store_name,
	sum(order_items.list_price * order_items.quantity * (1 - order_items.discount)) as total_revenue
from stores
join orders on orders.store_id = stores.store_id
join order_items on orders.order_id = order_items.order_id
group by store_name
order by total_revenue desc;

#answer: Rowlett Bikes are behind in total revenue 

#Task 2: Top 5 most sold products by quantity. 
# products table join order_items

select * from products;

select 
	products.product_name,
	sum(order_items.quantity) as total_quantities
from products
join order_items
on products.product_id = order_items.product_id
group by products.product_name 
order by total_quantities desc
limit 5;

#Task 3: Customers who placed orders with store names.
# bringing the name of customers who placed orders with each store names

select 
	concat(customers.first_name, ' ', customers.last_name) as full_name,
	stores.store_name
from customers
join orders on orders.customer_id = customers.customer_id
join stores on stores.store_id = orders.store_id;

#task 4: Total number of products per brand.

select * from brands;

select
	brands.brand_name,
	count(products.product_name) as total_products
from brands
inner join products on brands.brand_id = products.brand_id
group by brand_name 
order by total_products desc;

#task 5: Products with zero quantity in stock.
# displaying products name with quantities from order_items with 0

select *from stocks;

select
	products.product_name,
	stocks.quantity as zero_quantity
from products
join stocks on products.product_id = stocks.product_id
where stocks.quantity = 0;
	
